{"name": "test_login_failure_a", "status": "passed", "attachments": [{"name": "stdout", "source": "4e6e2105-eb33-4a68-80c9-9759e407c470-attachment.txt", "type": "text/plain"}], "start": 1731589496660, "stop": 1731589496660, "uuid": "d08339bf-99e8-422a-8df6-7e8945068d8e", "historyId": "91e525a053aeed59c11f58ac55c18533", "testCaseId": "91e525a053aeed59c11f58ac55c18533", "fullName": "test_feature_story.TestLogin#test_login_failure_a", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "用户名密码错误!"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "孤独二里"}, {"name": "thread", "value": "28396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}